/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperSettingsRouteImport } from './routes/super.settings'
import { Route as SuperHostelsRouteImport } from './routes/super.hostels'
import { Route as SuperDashboardRouteImport } from './routes/super.dashboard'
import { Route as SuperAnalyticsRouteImport } from './routes/super.analytics'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperSettingsRoute = SuperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperRoute,
} as any)
const SuperHostelsRoute = SuperHostelsRouteImport.update({
  id: '/hostels',
  path: '/hostels',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDashboardRoute = SuperDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAnalyticsRoute = SuperAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/super': typeof SuperRouteWithChildren
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/hostels': typeof SuperHostelsRoute
  '/super/settings': typeof SuperSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/hostels': typeof SuperHostelsRoute
  '/super/settings': typeof SuperSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/super': typeof SuperRouteWithChildren
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/hostels': typeof SuperHostelsRoute
  '/super/settings': typeof SuperSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/super'
    | '/super/analytics'
    | '/super/dashboard'
    | '/super/hostels'
    | '/super/settings'
    | '/admin/'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/super/analytics'
    | '/super/dashboard'
    | '/super/hostels'
    | '/super/settings'
    | '/admin'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/super'
    | '/super/analytics'
    | '/super/dashboard'
    | '/super/hostels'
    | '/super/settings'
    | '/admin/'
    | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SuperRoute: typeof SuperRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super/settings': {
      id: '/super/settings'
      path: '/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof SuperSettingsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/hostels': {
      id: '/super/hostels'
      path: '/hostels'
      fullPath: '/super/hostels'
      preLoaderRoute: typeof SuperHostelsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/dashboard': {
      id: '/super/dashboard'
      path: '/dashboard'
      fullPath: '/super/dashboard'
      preLoaderRoute: typeof SuperDashboardRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/analytics': {
      id: '/super/analytics'
      path: '/analytics'
      fullPath: '/super/analytics'
      preLoaderRoute: typeof SuperAnalyticsRouteImport
      parentRoute: typeof SuperRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperRouteChildren {
  SuperAnalyticsRoute: typeof SuperAnalyticsRoute
  SuperDashboardRoute: typeof SuperDashboardRoute
  SuperHostelsRoute: typeof SuperHostelsRoute
  SuperSettingsRoute: typeof SuperSettingsRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperAnalyticsRoute: SuperAnalyticsRoute,
  SuperDashboardRoute: SuperDashboardRoute,
  SuperHostelsRoute: SuperHostelsRoute,
  SuperSettingsRoute: SuperSettingsRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SuperRoute: SuperRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
